sudo: true
language: node_js
node_js:
  - "8"
  - "10"
before_script:
  - sudo apt-get install -y potrace librsvg2-bin imagemagick
install:
  - npm install -g coveralls
  - npm install
script:
  - npm run test:cover
  - cat ./coverage/lcov.info | coveralls
